title: NKThesis
description: 南开大学毕业论文 LaTeX 模板
theme: jekyll-theme-slate
show_downloads: true
github:
   zip_url: https://github.com/Tr0py/NKU-thesis-template-2020/releases/latest
   tar_url: https://github.com/Tr0py/NKU-thesis-template-2020/releases/latest
